name: hagglex
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.11
  charts_flutter: ^0.10.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  equatable: ^2.0.0
  flutter_dotenv: ^3.1.0
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.21.0+1
  flutter_switch: ^0.3.1
  get_it: ^4.0.1
  google_fonts: ^2.0.0
  gql: ^0.13.0-nullsafety.2
  graphql_flutter: ^5.0.0-nullsafety.2
  hive: ^2.0.4
  intl: ^0.17.0
  logger: ^0.9.4
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: BasisLight
      fonts:
        - asset: assets/fonts/BasisGrotesquePro-Light.ttf
    - family: BasisRegular
      fonts:
        - asset: assets/fonts/BasisGrotesquePro-Regular.ttf
    - family: BasisBold
      fonts:
        - asset: assets/fonts/BasisGrotesquePro-Bold.ttf
